services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
    networks:
      - my-network
  
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    
